export const CLEAR_PLANS = 'CLEAR_PLANS';
export const LOADING_INDICATOR = 'LOADING_INDICATOR';
export const RECEIVE_PLANS = 'RECEIVE_PLANS';
export const RELOAD_PLANS = 'RELOAD_PLANS';
export const SEARCH_PLANS = 'SEARCH_PLANS';
